### ISSUE TITLE
Human Protein Atlas edges not present in merged KG

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-idg#64]
### Describe the bug

Edges of type `biolink:expressed_in` appear to be correctly produced by the `ProteinAtlasTransform`, but are not present in the merged graph.

### To Reproduce

```
python run.py download
python run.py transform
# or 
# python run.py transform -s ProteinAtlasTransform 
# for single transform
python run.py merge
```

```
$ grep biolink:expressed_in data/merged/merged-kg_edges.tsv | wc -l
0
```

Transformed edges look like this:
```
uuid:92b106b2-5e89-11ec-bbc2-00155d00d735       UniProtKB:Q3KRB8        biolink:expressed_in    GO:0031982      biolink:GeneToExpressionSiteAssociation|biolink:Association     RO:0002206              Human Protein Atlas
```
and transformed nodes:
```
GO:0031982      biolink:AnatomicalEntity|biolink:NamedThing     vesicle         Human Protein Atlas
```

GO terms are present in the merged graph but GO is its own ingest.

## Expected behavior

Transformed edges such as that above should be present in the merged graph.

### Version

d21ccb9dd46af0acd0773674fad1e3a1e71bb8c8

**Comment by caufieldjh** [comment]
The intended association class is [GeneToExpressionSiteAssociation](https://biolink.github.io/biolink-model/docs/GeneToExpressionSiteAssociation.html)

**Comment by caufieldjh** [comment]
A minimal merge with the following merge.yaml:
```
---
configuration:
  output_directory: data/merged
  checkpoint: false
merged_graph:
  name: IDG graph
  source:
    hpa:
      name: "Human Proteome Atlas"
      input:
        format: tsv
        filename:
          - data/transformed/hpa/hpa-data_nodes.tsv
          - data/transformed/hpa/hpa-data_edges.tsv
  operations:
    - name: kgx.graph_operations.summarize_graph.generate_graph_stats
      args:
        graph_name: IDG Graph
        filename: merged_graph_stats.yaml
        node_facet_properties:
          - provided_by
        edge_facet_properties:
          - provided_by
  destination:
    merged-kg-tsv:
      format: tsv
      compression: tar.gz
      filename: merged-kg-test
```
appears to correctly add the expressed_in edges:
```
$ head hpa-data_edges.tsv
id      subject predicate       object  category        relation        provided_by     source
uuid:88b84f62-5e89-11ec-bbc2-00155d00d735       UniProtKB:O43657        biolink:expressed_in    GO:0005829      biolink:GeneToExpressionSiteAssociation|biolink:Association     RO:0002206              Human Protein Atlas
uuid:88b84f62-5e89-11ec-bbc2-00155d00d735       UniProtKB:O43657        biolink:expressed_in    GO:0005829      biolink:GeneToExpressionSiteAssociation|biolink:Association     RO:0002206              Human Protein Atlas
uuid:88b84f62-5e89-11ec-bbc2-00155d00d735       UniProtKB:O43657        biolink:expressed_in    GO:0005829      biolink:GeneToExpressionSiteAssociation|biolink:Association     RO:0002206              Human Protein Atlas
```
